stages:
  - clean
  - build
  - deploy

image: maven:3.6-jdk-11

clean-project:
  stage : clean
  script: mvn clean

build-project:
  stage : build
  script: mvn package

deploy:
  stage : deploy
  script: mvn deploy -s ci_settings.xml

