stages:
  - clean
  - deploy

image: maven:3.6-jdk-11

clean-project:
  stage : clean
  script: mvn clean -f dev/pom.xml


deploy:
  stage : deploy
  script: 
  - mvn package -f dev/pom.xml -DfinalName=Comics_Library 
  - ls -l dev/target/
  - mvn deploy:deploy-file  -s ci_settings.xml -f dev/pom.xml -DfinalName=Comics_Library -Dfile=target/Comics_Library.jar -Dpackaging=jar -Durl=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven

