stages:
  - clean
  - build
  - deploy

clean-project:
  stage : clean
  script: mvn clean

build-project:
  stage : build
  script: mvn package

deploy:
  stage : deploy
  script: mvn deploy
  only:
    - develop
    - main
