stages:
  - clean
  - build
  - deploy

image: maven:3.6-jdk-11

clean-project:
  stage : clean
  script: mvn clean -f dev/pom.xml

build-project:
  stage : build
  script: mvn package -f dev/pom.xml

deploy:
  stage : deploy
  script: mvn deploy -s ci_settings.xml -f dev/pom.xml

rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
